companies/urls.py
from django.conf.urls import url

from . import views
from .views import CompanyDetailView

app_name = 'companies'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CompanyDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'core'

urlpatterns = [
    url(r'^login/success/', views.login_redirect, name='login_redirect'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='core/login.html', extra_context={'next': 'success/'}), name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
]

improveon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^tools/', include('tools.urls')),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

jobs/urls.py
from django.conf.urls import url

from . import views
from .views import JobDetailView


app_name = 'jobs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

companies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver

from core.models import TimeStampedModel
from core.signals import create_company

# Create your models here.
class Company(TimeStampedModel):

    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100, null=True)
    bio = models.CharField(max_length=1000, blank=True)
    likes = models.IntegerField(default=0)
    anonymous = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'companies'


@receiver(create_company, sender=User)
def update_user_company(sender, **kwargs):
    instance = kwargs['instance']
    Company.objects.create(user=instance)
    instance.company.save()

companies/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    bio = forms.CharField(max_length=2000)
    anonymous = forms.BooleanField(required=False)
    name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'bio', 'anonymous', 'password1', 'password2', )

companies/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect

from jobs.models import Job

from .models import Company
from .forms import SignUpForm
from core.signals import create_company


# Create your views here.
def index(request):
    companies = Company.objects.all()[:5]
    return render(request, 'companies/index.html', context={'companies': companies})


class CompanyDetailView(DetailView):
    model = Company

@permission_required('companies.change_company', login_url=reverse_lazy('core:login'))
@login_required(login_url=reverse_lazy('core:login'))
def overview(request):
    company_user = None
    if request.user.is_authenticated():
        company_user = User.objects.get(username=request.user)

    company = Company.objects.get(user=company_user)
    jobs = Job.objects.filter(company=company)
    return render(request, 'companies/overview.html', context={'company': company, 'jobs': jobs})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            create_company.send(sender=User, instance=user)
            user.refresh_from_db()  # load the profile instance created by the signal
            user.company.name = form.cleaned_data.get('name')
            user.company.bio = form.cleaned_data.get('bio')
            user.company.anonymous = form.cleaned_data.get('anonymous')
            user.groups.set(['companies'])
            user.company.save()
            raw_password = form.clean_password2()
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('companies:overview')
    else:
        form = SignUpForm()
    return render(request, 'companies/signup.html', {'form': form})

companies/templates/companies/company_detail.html
{% extends "base.html" %}

{% block title %}{{ company.name }}{% endblock %}

{% block content %}
    <h3>{{ company.name }}</h3>

    <p>{{ company.bio }}</p>
{% endblock %}

companies/templates/companies/index.html
{% extends "base.html" %}

{% block title %}Companies{% endblock %}

{% block content %}
    <h3>Companies</h3>
    <p>This is the companies index page.</p>

    <ul>
    {% for company in companies %}
    <li><a href="{% url 'companies:detail' company.id %}">{{ company.name }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

companies/templates/companies/overview.html
{% extends "base.html" %}

{% block title %}Overview{% endblock %}

{% block content %}
    <h4>Information</h4>
    <table>
        <tr>
            <td>Name</td>
            <td>{{ company.name }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ company.bio }}</td>
        </tr>
        <tr>
            <td>Likes</td>
            <td>{{ company.likes }}</td>
        </tr>
    </table>

    <h4>Your jobs</h4>
    <ul>
    {% for job in jobs %}
        <li><a href="{% url 'jobs:detail' job.id %}">{{ job.name }}</a></li>
    {% endfor %}
    </ul>

    <p>Register new job <a href="{% url 'jobs:register' %}">here.</a></p>
{% endblock %}

companies/templates/companies/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="button" type="submit">Sign up</button>
  </form>
{% endblock %}