core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'core'

urlpatterns = [
    url(r'^login/success/', views.login_redirect, name='login_redirect'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='core/login.html', extra_context={'next': 'success/'}), name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
]

improveon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^tools/', include('tools.urls')),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

students/urls.py
from django.conf.urls import url

from . import views
from .views import StudentDetailView


app_name = 'students'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', StudentDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^change/', views.change_info, name='change'),
]

tools/urls.py
from django.conf.urls import url

from . import views
from .views import ToolDetailView


app_name = 'tools'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', ToolDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

students/models.py
from django.db import models
from django.contrib.auth.models import User
from core.signals import create_student
from django.dispatch import receiver


# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    bio = models.CharField(max_length=1000, blank=True)
    phone_number = models.IntegerField(blank=True, null=True)
    resume = models.FileField(null=True)
    photo = models.ImageField(null=True)

    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name


def update_user_student(sender, **kwargs):
    instance = kwargs['instance']
    Student.objects.create(user=instance)
    instance.student.save()

create_student.connect(update_user_student)

students/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Student


class SignUpForm(UserCreationForm):
    bio = forms.CharField(max_length=2000)
    phone_number = forms.IntegerField(max_value=999999999999)
    resume = forms.FileField(required=False)
    photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'bio', 'phone_number', 'password1', 'password2', 'resume', 'photo')


class ChangeForm(forms.ModelForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = Student
        fields = ['email', 'bio', 'phone_number', 'resume', 'photo']

students/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.contrib.auth import login, authenticate
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.core.files.images import ImageFile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from tools.models import Tool

from .models import Student
from .forms import SignUpForm, ChangeForm
from core.signals import create_student


# Create your views here.
def index(request):
    student_list = Student.objects.all().order_by('-id')
    paginator = Paginator(student_list, 6)

    page = request.GET.get('page')
    try:
        students = paginator.page(page)
    except PageNotAnInteger:
        students = paginator.page(1)
    except EmptyPage:
        students = paginator.page(paginator.num_pages)


    return render(request, 'students/index.html', context={'students': students})

class StudentDetailView(DetailView):
    model = Student

    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        context['tools'] = Tool.objects.filter(author=context['student'])
        return context

@permission_required('students.change_student', login_url=reverse_lazy('core:login'))
@login_required(login_url=reverse_lazy('core:login'))
def overview(request):
    student_user = None
    if request.user.is_authenticated():
        student_user = User.objects.get(username=request.user)

    try:
        student = Student.objects.get(user=student_user)
    except ObjectDoesNotExist:
        return render(request, 'core/index.html')

    tools = Tool.objects.filter(author=student)
    return render(request, 'students/overview.html', context={'student': student, 'tools': tools})

@permission_required('students.change_student', login_url=reverse_lazy('core:login'))
@login_required(login_url=reverse_lazy('core:login'))
def change_info(request):
    student_user = None
    if request.user.is_authenticated():
        student_user = User.objects.get(username=request.user)

    try:
        student = Student.objects.get(user=student_user)
    except ObjectDoesNotExist:
        return render(request, 'core/index.html')

    if request.method == 'POST':
        form = ChangeForm(request.POST, request.FILES, instance=student)
        if form.is_valid():
            student_user.email = form.cleaned_data['email']
            form.save()
            return redirect('students:overview')
    else:
        form = ChangeForm(instance=student)

    return render(request, 'students/signup.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            create_student.send(sender=User, instance=user)
            user.refresh_from_db()  # load the profile instance created by the signal
            user.student.bio = form.cleaned_data.get('bio')
            user.student.phone_number = form.cleaned_data.get('phone_number')
            user.student.resume = File(request.FILES['resume'])
            user.student.photo = ImageFile(request.FILES['photo'])

            # Add user to group
            students_group = Group.objects.get(name='students')
            user.groups.set([students_group])
            user.student.save()
            raw_password = form.clean_password2()
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('students:overview')
    else:
        form = SignUpForm()
    return render(request, 'students/signup.html', {'form': form})

students/templates/students/index.html
{% extends "base.html" %}

{% block title %}Students{% endblock %}

{% block content %}
    <h3>Students</h3>

    <div class="row marketing">
        {% for student in students %}
            <div class="col-lg-4">
                {% if student.photo %}
                    <img class="rounded-circle" src="{{ student.photo.url }}" alt="Generic placeholder image" width="140" height="140">
                {% else %}
                    <img class="rounded-circle" src="{{ MEDIA_URL }}grey.gif" alt="Generic placeholder image" width="140" height="140">
                {% endif %}
                <h2>{{ student.user.first_name }}</h2>
                <p>{{ student.bio }}</p>
                <p><a class="btn btn-secondary" href="{% url 'students:detail' student.id %}" role="button">View student &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        {% endfor %}
    </div><!-- /.row -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if students.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ students.previous_page_number }}">Previous</a></li>
                {% endif %}
                <li class="page-item"><a class="page-link" href="#">{{ students.number }}</a></li>
                {% if students.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ students.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>

{% endblock %}

students/templates/students/overview.html
{% extends "base.html" %}

{% block title %}Overview{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if student.photo %}
                    <img class="img-fluid" src="{{ student.photo.url }}" alt="{{ student.photo.name }}">
                {% endif %}
            </div>
            <div class="col-md-9">
                <h4>Information</h4>
                <table class="table">
                    <tr>
                        <td>First name</td>
                        <td>{{ student.user.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Last name</td>
                        <td>{{ student.user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Bio</td>
                        <td>{{ student.bio }}</td>
                    </tr>
                    <tr>
                        <td>Resume</td>
                        <td>{% if student.resume %}<a href="{{ student.resume.url }}">{{ student.resume.name }}</a>{% else %}None{% endif %}</td>
                    </tr>
                </table>
                <a class="btn btn-primary" href="{% url 'students:change' %}">Change</a>
            </div>
        </div>
    </div>


    <h4>Your tools</h4>
    <ul>
        {% for tool in tools %}
            <li><a href="{% url 'tools:detail' tool.id %}">{{ tool.name }}</a></li>
        {% endfor %}
    </ul>

    <p>Register new tool <a href="{% url 'tools:register' %}">here.</a></p>
{% endblock %}

students/templates/students/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="button" type="submit">Sign up</button>
  </form>
{% endblock %}

students/templates/students/student_detail.html
{% extends "base.html" %}

{% block title %}{{ student.user.first_name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {% if student.photo %}
                    <img class="img-fluid" src="{{ student.photo.url }}" alt="{{ student.photo.name }}">
                {% endif %}
            </div>
            <div class="col-md-9">
                <h4>Information</h4>
                <table class="table">
                    <tr>
                        <td>First name</td>
                        <td>{{ student.user.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Last name</td>
                        <td>{{ student.user.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Bio</td>
                        <td>{{ student.bio }}</td>
                    </tr>
                    <tr>
                        <td>Resume</td>
                        <td>{% if student.resume %}<a href="{{ student.resume.url }}">{{ student.resume.name }}</a>{% else %}None{% endif %}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>


    <h4>{{ student.user.first_name }}'s tools</h4>
    <ul>
        {% for tool in tools %}
            <li><a href="{% url 'tools:detail' tool.id %}">{{ tool.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}