companies/urls.py
from django.conf.urls import url

from . import views
from .views import CompanyDetailView

app_name = 'companies'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CompanyDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'core'

urlpatterns = [
    url(r'^login/success/', views.login_redirect, name='login_redirect'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='core/login.html', extra_context={'next': 'success/'}), name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
]

improveon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^tools/', include('tools.urls')),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

jobs/urls.py
from django.conf.urls import url

from . import views
from .views import JobDetailView


app_name = 'jobs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

students/urls.py
from django.conf.urls import url

from . import views
from .views import StudentDetailView


app_name = 'students'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', StudentDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^change/', views.change_info, name='change'),
]

tools/urls.py
from django.conf.urls import url

from . import views
from .views import ToolDetailView


app_name = 'tools'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', ToolDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

core/models.py
from django.db import models


# Create your models here.
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect

from students.models import Student
from companies.models import Company
from tools.models import Tool
from jobs.models import Job


# Create your views here.
@login_required(login_url='core/login.html')
def login_redirect(request):
    user_login = None
    student_or_company = None
    student = False
    if request.user.is_authenticated():
        user_login = User.objects.get(username=request.user)

    try:
        student_or_company = Student.objects.get(user=user_login)
        student = True
    except ObjectDoesNotExist:
        try:
            student_or_company = Company.objects.get(user=user_login)
        except:
            print('No company or student found.')

    if student_or_company is None:
        return render(request, 'core/login.html')

    if student:
        return redirect('students:overview')
    else:
        return redirect('companies:overview')

def index(request):
    jobs = Job.objects.all()[:3]
    tools = Tool.objects.all()[:3]
    return render(request, 'core/index.html', context={'jobs': jobs, 'tools': tools})

def signup(request):
    return render(request, 'core/signup.html')

# TODO Improve search function
def search(request):
    if request.method == 'GET':
        search_list = request.GET.get('q')
        try:
            students = Student.objects.filter(bio__icontains=search_list)
            return render(request, 'core/search.html', context={'students': students})
        except:
            pass

    return render(request, 'core/search.html')

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}


{% block content %}
    {% if not user.is_authenticated %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Welcome!</h1>
            <p>Find out how, as a company, you can benefit from using this platform by using student-made tools or place a job to let a student create a tool for you.
            Students, find out how you can give your career a boost by creating tools used by real companies.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>
    {% endif %}

    <h2>Tools</h2>
    <div class="row">
    {% for tool in tools %}
        <div class="col-md-4 card">
            <div class="card-body">
                <h5 class="card-title">{{ tool.name }}</h5>
                <p class="card-text">{{ tool.description }}</p>
                <a class="btn btn-secondary" href="{% url 'tools:detail' tool.id %}" role="button">View details &raquo;</a>
            </div>
        </div>
    {% endfor %}
    </div>

    <h2>Jobs</h2>
    <div class="row">
    {% for job in jobs %}
        <div class="col-md-4 card">
            <div class="card-body">
                <h5 class="card-title">{{ job.name }}</h5>
                <p class="card-text">{{ job.description }}</p>
                <a class="btn btn-secondary" href="{% url 'jobs:detail' job.id %}" role="button">View details &raquo;</a>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}

core/templates/core/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}


{% block content %}

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'core:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" class="button" value="login" />
    <input type="hidden" name="next" value="{{ next }}" />
    </form>

    <p>Not registred yet? Sign up <a href="{% url 'core:signup' %}">here.</a></p>

{% endblock %}

core/templates/core/logout.html
{% extends "base.html" %}

{% block title %}Logout{% endblock %}


{% block content %}

    <p>You're logged out.</p>

{% endblock %}

core/templates/core/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}


{% block content %}
<h3>Search results:</h3>
{% if students %}
    <ul>
{% for student in students %}
     <li>{{ student.user.first_name }}</li>
{% endfor %}
    </ul>
{% endif %}

{% endblock %}

core/templates/core/signup.html
{% extends "base.html" %}

{% block title %}Logout{% endblock %}


{% block content %}

    <ul>
        <li><a class="button" href="{% url 'students:signup' %}">Student</a></li>
        <li><a class="button" href="{% url 'companies:signup' %}">Company</a></li>
    </ul>

{% endblock %}