companies/urls.py
from django.conf.urls import url

from . import views
from .views import CompanyDetailView

app_name = 'companies'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', CompanyDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
]

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'core'

urlpatterns = [
    url(r'^login/success/', views.login_redirect, name='login_redirect'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='core/login.html', extra_context={'next': 'success/'}), name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^search/', views.search, name='search'),
]

improveon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^students/', include('students.urls')),
    url(r'^tools/', include('tools.urls')),
    url(r'^jobs/', include('jobs.urls')),
    url(r'^companies/', include('companies.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

jobs/urls.py
from django.conf.urls import url

from . import views
from .views import JobDetailView


app_name = 'jobs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', JobDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

students/urls.py
from django.conf.urls import url

from . import views
from .views import StudentDetailView


app_name = 'students'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', StudentDetailView.as_view(), name='detail'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^change/', views.change_info, name='change'),
]

tools/urls.py
from django.conf.urls import url

from . import views
from .views import ToolDetailView


app_name = 'tools'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', ToolDetailView.as_view(), name='detail'),
    url(r'^register/', views.register, name='register'),
]

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} | ImproveOn</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'core:index' %}">ImproveOn</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li><a class="nav-link" href="{% url 'companies:index' %}">Companies</a></li>
            <li><a class="nav-link" href="{% url 'jobs:index' %}">Jobs</a></li>
            <li><a class="nav-link" href="{% url 'tools:index' %}">Tools</a></li>
            <li><a class="nav-link" href="{% url 'students:index' %}">Students</a></li>
        </ul>

        <form class="form-inline my-2 my-lg-0" action="{% url 'core:search' %}" method="get">
            <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="nav navbar-nav">
        {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'core:login_redirect' %}">Overview</a></li>
            <li><a class="nav-link" href="{% url 'core:logout' %}">Log out</a></li>
        {% else %}
            <li><a class="nav-link" href="{% url 'core:login' %}">Log in</a></li>
        {% endif %}
    </ul>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}

    <hr>

    <footer>
        <p>&copy; Company 2017</p>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

</body>
</html>